In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV

In [4]:
train_df = pd.read_csv("data/train.csv")

In [6]:
train_df.head()

,id,f_00,f_01,f_02,f_03,f_04,f_05,f_06,f_07,f_08,...,f_22,f_23,f_24,f_25,f_26,f_27,f_28,f_29,f_30,target
0,0,-1.373246,0.238887,-0.243376,0.567405,-0.647715,0.839326,0.113133,1,5,...,-2.540739,0.766952,-2.730628,-0.208177,1.363402,ABABDADBAB,67.609153,0,0,0
1,1,1.697021,-1.710322,-2.230332,-0.545661,1.113173,-1.552175,0.447825,1,3,...,2.278315,-0.633658,-1.217077,-3.782194,-0.058316,ACACCADCEB,377.096415,0,0,1
2,2,1.681726,0.616746,-1.027689,0.810492,-0.609086,0.113965,-0.708660,1,0,...,-1.385775,-0.520558,-0.009121,2.788536,-3.703488,AAAEABCKAD,-195.599702,0,2,1
3,3,-0.118172,-0.587835,-0.804638,2.086822,0.371005,-0.128831,-0.282575,3,2,...,0.572594,-1.653213,1.686035,-2.533098,-0.608601,BDBBAACBCB,210.826205,0,0,1
4,4,1.148481,-0.176567,-0.664871,-1.101343,0.467875,0.500117,0.407515,3,3,...,-3.912929,-1.430366,2.127649,-3.306784,4.371371,BDBCBBCHFE,-217.211798,0,1,1

In [7]:
X = train_df.iloc[: , :8]
y = train_df.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test) # predict on X_test set
print("Score", knn.score(X_test, y_test), "\n")
print("Confusion Matrix", confusion_matrix(y_test, y_pred), "\n")
print("Classification Report\n", classification_report(y_test, y_pred), "\n")

Score 0.5023333333333333

Confusion Matrix [[72547 66101]
 [68269 63083]]

Classification Report
               precision    recall  f1-score   support

           0       0.52      0.52      0.52    138648
           1       0.49      0.48      0.48    131352

    accuracy                           0.50    270000
   macro avg       0.50      0.50      0.50    270000
weighted avg       0.50      0.50      0.50    270000

In [ ]:
train_accuracies = []
test_accuracies = []
neighbors_range = range(1, 10)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
for no_neighbors in neighbors_range:
    knn = KNeighborsClassifier(n_neighbors=no_neighbors)
    knn.fit(X_train, y_train)
    train_accuracies.append(knn.score(X_train, y_train))
    test_accuracies.append(knn.score(X_test, y_test))

plt.plot(neighbors_range, train_accuracies, label="Training accuracy")
plt.plot(neighbors_range, test_accuracies, label="Test accuracy")
plt.legend()
plt.show()
print("No. neighbours for highest score:", neighbors_range[np.argmax(test_accuracies)])